language: node_js
deploy:
  provider: npm
  email: mail@sebakrau.de
  api_key:
    secure: fdkG4LXaGhaNJ1qT28gwhPi4Tdf8jUsNDSGM2Sx0nB5b3xsdWQr/eWXWV0hZa8TlFYsgOcfpRKxoDc2QAWoLx2Bj9uLBnmMxUiWkii5uytZXYdwDZRv92wi3vJS5OGyvqo/AvXj0nQt+DAPRq6q/Yea/uKWNI3w13mJQaK8oHAZBgLRbuaWHeAQYq4dJtL4ZBM32EesaQqCv3R0r4FCprUWgh5p7tnj73s8X017JS3WySbD2IfGZvp6aiv7iqq4uxjZndSVEBz4ryGA8LCPq9yEvnvu03OxP6jRF942TAK24wCs5p2tsTZqQwPHKtAVP9aCniZe1a/I9DSAlaYUP8jQtBq1wcWXIEdyVLrUonEa8wiXb2xRyBK1G/IQfSUX1pOTSSa/POOKewCZMjUEXOvyfTDMQ4AQT1anwi56rZo9gOsnNqH4ba7JhCev03/SkvPfIUJMCOaI5wX9iwUCgFt6lGANq/itBE0GcC6Y422rGyGzS3Cy7/EqRGMJDN+8ib3ZaXJBoncZf5Zalk3evADqMjBgNVOgJnLkqg7AZwOLDyC6zzHicpgAEAxH35cRNJsPjDMWxaF05VmtAdqlWiHUTHjdvz9L0D7Uvw336mImFiJJPcJf9X8m0G4YlFRmp8PFqqq37eL1NK56KGGxSjl4wRShchulJVbLgGEbGnXw=
  on:
    tags: true
    branch: master